"""fresh_start

Revision ID: 943dee823e07
Revises: 
Create Date: 2026-07-16 04:59:17.179402
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.database.types

revision = '943dee823e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_status',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_status_name'), 'lead_status', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('vendors',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendors_category', 'vendors', ['category'], unique=False)
    op.create_index('ix_vendors_name', 'vendors', ['name'], unique=False)
    op.create_table('websites',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_api_key'), 'websites', ['api_key'], unique=True)
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_table('whatsapp_interactions',
    sa.Column('interaction_type', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_interactions_phone', 'whatsapp_interactions', ['phone'], unique=False)
    op.create_index('ix_whatsapp_interactions_type', 'whatsapp_interactions', ['interaction_type'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_whatsapp_templates_name', 'whatsapp_templates', ['name'], unique=False)
    op.create_index('ix_whatsapp_templates_type', 'whatsapp_templates', ['template_type'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', app.database.types.GUID(), nullable=False),
    sa.Column('permission_id', app.database.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', app.database.types.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approval_requests',
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', app.database.types.GUID(), nullable=False),
    sa.Column('approver_id', app.database.types.GUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_approver_id', 'approval_requests', ['approver_id'], unique=False)
    op.create_index('ix_approval_requests_module', 'approval_requests', ['module'], unique=False)
    op.create_index('ix_approval_requests_requested_by', 'approval_requests', ['requested_by'], unique=False)
    op.create_index('ix_approval_requests_status', 'approval_requests', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', app.database.types.GUID(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_platform'), 'campaigns', ['platform'], unique=False)
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('alternate_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('anniversary_date', sa.Date(), nullable=True),
    sa.Column('partner_user_id', app.database.types.GUID(), nullable=True),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_partner_user_id', 'customers', ['partner_user_id'], unique=False)
    op.create_index('ix_customers_phone', 'customers', ['phone'], unique=False)
    op.create_table('finance_ledger_entries',
    sa.Column('entry_type', sa.String(length=64), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_no', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finance_ledger_entries_entry_date', 'finance_ledger_entries', ['entry_date'], unique=False)
    op.create_index('ix_finance_ledger_entries_entry_type', 'finance_ledger_entries', ['entry_type'], unique=False)
    op.create_table('hr_employees',
    sa.Column('user_id', app.database.types.GUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('designation', sa.String(length=64), nullable=True),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('incentives', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_employees_department', 'hr_employees', ['department'], unique=False)
    op.create_index('ix_hr_employees_user_id', 'hr_employees', ['user_id'], unique=False)
    op.create_table('lead_saved_views',
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_saved_views_user_id', 'lead_saved_views', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('developer_name', sa.String(length=200), nullable=False),
    sa.Column('sole_selling_partner', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('project_status', sa.String(length=64), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('sold_inventory', sa.Integer(), nullable=False),
    sa.Column('price_list', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payment_plans', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gallery', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('videos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('brochure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('legal_status', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('nearby_landmarks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_location', 'projects', ['location'], unique=False)
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['project_status'], unique=False)
    op.create_table('sales_team_reports',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('sales_executive_id', app.database.types.GUID(), nullable=False),
    sa.Column('sales_executive_name', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('achieved_sales_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bookings_count', sa.Integer(), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('site_visits_count', sa.Integer(), nullable=False),
    sa.Column('attendance_status', sa.String(length=32), nullable=False),
    sa.Column('daily_report', sa.Text(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_team_reports_report_date', 'sales_team_reports', ['report_date'], unique=False)
    op.create_index('ix_sales_team_reports_sales_executive_id', 'sales_team_reports', ['sales_executive_id'], unique=False)
    op.create_table('site_visits',
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_time', sa.Time(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('sales_executive', sa.String(length=200), nullable=False),
    sa.Column('pickup_required', sa.Boolean(), nullable=False),
    sa.Column('vehicle_assigned', sa.String(length=128), nullable=True),
    sa.Column('driver', sa.String(length=128), nullable=True),
    sa.Column('attendance', sa.String(length=32), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=True),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_site_visits_customer_name', 'site_visits', ['customer_name'], unique=False)
    op.create_index('ix_site_visits_sales_executive', 'site_visits', ['sales_executive'], unique=False)
    op.create_index('ix_site_visits_visit_date', 'site_visits', ['visit_date'], unique=False)
    op.create_table('bookings',
    sa.Column('customer_id', app.database.types.GUID(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('booking_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sales_executive_id', app.database.types.GUID(), nullable=True),
    sa.Column('partner_user_id', app.database.types.GUID(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_executive_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_customer_id', 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_partner_user_id', 'bookings', ['partner_user_id'], unique=False)
    op.create_index('ix_bookings_sales_executive_id', 'bookings', ['sales_executive_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_table('hr_records',
    sa.Column('employee_id', app.database.types.GUID(), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hr_records_employee_id', 'hr_records', ['employee_id'], unique=False)
    op.create_index('ix_hr_records_record_date', 'hr_records', ['record_date'], unique=False)
    op.create_index('ix_hr_records_record_type', 'hr_records', ['record_type'], unique=False)
    op.create_table('inventory_units',
    sa.Column('project_id', app.database.types.GUID(), nullable=False),
    sa.Column('plot_no', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=False),
    sa.Column('facing', sa.String(length=64), nullable=True),
    sa.Column('is_corner', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('booking_status', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('sales_executive', sa.String(length=200), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=True),
    sa.Column('agreement_status', sa.String(length=64), nullable=True),
    sa.Column('payment_status', sa.String(length=64), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_units_booking_status', 'inventory_units', ['booking_status'], unique=False)
    op.create_index('ix_inventory_units_plot_no', 'inventory_units', ['plot_no'], unique=False)
    op.create_index('ix_inventory_units_project_id', 'inventory_units', ['project_id'], unique=False)
    op.create_table('leads',
    sa.Column('website_id', app.database.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('medium', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', app.database.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', app.database.types.GUID(), nullable=True),
    sa.Column('extra_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_assigned_status', 'leads', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_campaign_created_at', 'leads', ['campaign_id', 'created_at'], unique=False)
    op.create_index('ix_leads_campaign_id', 'leads', ['campaign_id'], unique=False)
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_email', 'leads', ['email'], unique=False)
    op.create_index('ix_leads_extra_data_gin', 'leads', ['extra_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_created_at', 'leads', ['status', 'created_at'], unique=False)
    op.create_table('seo_keywords',
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('target_position', sa.Integer(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('traffic', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('campaign_id', app.database.types.GUID(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_keywords_keyword'), 'seo_keywords', ['keyword'], unique=False)
    op.create_table('customer_payments',
    sa.Column('customer_id', app.database.types.GUID(), nullable=False),
    sa.Column('booking_id', app.database.types.GUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_mode', sa.String(length=32), nullable=False),
    sa.Column('reference_no', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', app.database.types.GUID(), nullable=False),
    sa.Column('partner_user_id', app.database.types.GUID(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_payments_booking_id', 'customer_payments', ['booking_id'], unique=False)
    op.create_index('ix_customer_payments_customer_id', 'customer_payments', ['customer_id'], unique=False)
    op.create_index('ix_customer_payments_partner_user_id', 'customer_payments', ['partner_user_id'], unique=False)
    op.create_index('ix_customer_payments_payment_date', 'customer_payments', ['payment_date'], unique=False)
    op.create_index('ix_customer_payments_reference_no', 'customer_payments', ['reference_no'], unique=False)
    op.create_table('document_assets',
    sa.Column('customer_id', app.database.types.GUID(), nullable=True),
    sa.Column('booking_id', app.database.types.GUID(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', app.database.types.GUID(), nullable=False),
    sa.Column('partner_user_id', app.database.types.GUID(), nullable=True),
    sa.Column('file_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_assets_booking_id', 'document_assets', ['booking_id'], unique=False)
    op.create_index('ix_document_assets_category', 'document_assets', ['category'], unique=False)
    op.create_index('ix_document_assets_customer_id', 'document_assets', ['customer_id'], unique=False)
    op.create_index('ix_document_assets_partner_user_id', 'document_assets', ['partner_user_id'], unique=False)
    op.create_index('ix_document_assets_storage_key', 'document_assets', ['storage_key'], unique=True)
    op.create_table('followups',
    sa.Column('lead_id', app.database.types.GUID(), nullable=False),
    sa.Column('assigned_to', app.database.types.GUID(), nullable=False),
    sa.Column('followup_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_followup_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('call_notes', sa.Text(), nullable=True),
    sa.Column('whatsapp_notes', sa.Text(), nullable=True),
    sa.Column('meeting_notes', sa.Text(), nullable=True),
    sa.Column('voice_recording_url', sa.Text(), nullable=True),
    sa.Column('sms_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('followup_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('auto_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('customer_id', app.database.types.GUID(), nullable=False),
    sa.Column('booking_id', app.database.types.GUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.database.types.GUID(), nullable=False),
    sa.Column('partner_user_id', app.database.types.GUID(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_booking_id', 'invoices', ['booking_id'], unique=False)
    op.create_index('ix_invoices_customer_id', 'invoices', ['customer_id'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    op.create_index('ix_invoices_partner_user_id', 'invoices', ['partner_user_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('lead_activity',
    sa.Column('lead_id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telecalling_calls',
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('telecaller_id', app.database.types.GUID(), nullable=False),
    sa.Column('lead_id', app.database.types.GUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('call_duration_sec', sa.Integer(), nullable=False),
    sa.Column('call_recording_url', sa.String(length=1024), nullable=True),
    sa.Column('daily_target', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telecaller_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telecalling_calls_call_date', 'telecalling_calls', ['call_date'], unique=False)
    op.create_index('ix_telecalling_calls_status', 'telecalling_calls', ['status'], unique=False)
    op.create_index('ix_telecalling_calls_telecaller_id', 'telecalling_calls', ['telecaller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telecalling_calls_telecaller_id', table_name='telecalling_calls')
    op.drop_index('ix_telecalling_calls_status', table_name='telecalling_calls')
    op.drop_index('ix_telecalling_calls_call_date', table_name='telecalling_calls')
    op.drop_table('telecalling_calls')
    op.drop_table('lead_activity')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_partner_user_id', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_customer_id', table_name='invoices')
    op.drop_index('ix_invoices_booking_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('followups')
    op.drop_index('ix_document_assets_storage_key', table_name='document_assets')
    op.drop_index('ix_document_assets_partner_user_id', table_name='document_assets')
    op.drop_index('ix_document_assets_customer_id', table_name='document_assets')
    op.drop_index('ix_document_assets_category', table_name='document_assets')
    op.drop_index('ix_document_assets_booking_id', table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index('ix_customer_payments_reference_no', table_name='customer_payments')
    op.drop_index('ix_customer_payments_payment_date', table_name='customer_payments')
    op.drop_index('ix_customer_payments_partner_user_id', table_name='customer_payments')
    op.drop_index('ix_customer_payments_customer_id', table_name='customer_payments')
    op.drop_index('ix_customer_payments_booking_id', table_name='customer_payments')
    op.drop_table('customer_payments')
    op.drop_index(op.f('ix_seo_keywords_keyword'), table_name='seo_keywords')
    op.drop_table('seo_keywords')
    op.drop_index('ix_leads_status_created_at', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_extra_data_gin', table_name='leads', postgresql_using='gin')
    op.drop_index('ix_leads_email', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    op.drop_index('ix_leads_campaign_id', table_name='leads')
    op.drop_index('ix_leads_campaign_created_at', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_index('ix_leads_assigned_status', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_inventory_units_project_id', table_name='inventory_units')
    op.drop_index('ix_inventory_units_plot_no', table_name='inventory_units')
    op.drop_index('ix_inventory_units_booking_status', table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_index('ix_hr_records_record_type', table_name='hr_records')
    op.drop_index('ix_hr_records_record_date', table_name='hr_records')
    op.drop_index('ix_hr_records_employee_id', table_name='hr_records')
    op.drop_table('hr_records')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_sales_executive_id', table_name='bookings')
    op.drop_index('ix_bookings_partner_user_id', table_name='bookings')
    op.drop_index('ix_bookings_customer_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_site_visits_visit_date', table_name='site_visits')
    op.drop_index('ix_site_visits_sales_executive', table_name='site_visits')
    op.drop_index('ix_site_visits_customer_name', table_name='site_visits')
    op.drop_table('site_visits')
    op.drop_index('ix_sales_team_reports_sales_executive_id', table_name='sales_team_reports')
    op.drop_index('ix_sales_team_reports_report_date', table_name='sales_team_reports')
    op.drop_table('sales_team_reports')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_index('ix_projects_location', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_lead_saved_views_user_id', table_name='lead_saved_views')
    op.drop_table('lead_saved_views')
    op.drop_index('ix_hr_employees_user_id', table_name='hr_employees')
    op.drop_index('ix_hr_employees_department', table_name='hr_employees')
    op.drop_table('hr_employees')
    op.drop_index('ix_finance_ledger_entries_entry_type', table_name='finance_ledger_entries')
    op.drop_index('ix_finance_ledger_entries_entry_date', table_name='finance_ledger_entries')
    op.drop_table('finance_ledger_entries')
    op.drop_index('ix_customers_phone', table_name='customers')
    op.drop_index('ix_customers_partner_user_id', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_campaigns_platform'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_requests_status', table_name='approval_requests')
    op.drop_index('ix_approval_requests_requested_by', table_name='approval_requests')
    op.drop_index('ix_approval_requests_module', table_name='approval_requests')
    op.drop_index('ix_approval_requests_approver_id', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index('ix_whatsapp_templates_type', table_name='whatsapp_templates')
    op.drop_index('ix_whatsapp_templates_name', table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index('ix_whatsapp_interactions_type', table_name='whatsapp_interactions')
    op.drop_index('ix_whatsapp_interactions_phone', table_name='whatsapp_interactions')
    op.drop_table('whatsapp_interactions')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_index(op.f('ix_websites_api_key'), table_name='websites')
    op.drop_table('websites')
    op.drop_index('ix_vendors_name', table_name='vendors')
    op.drop_index('ix_vendors_category', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_lead_status_name'), table_name='lead_status')
    op.drop_table('lead_status')
    # ### end Alembic commands ###
