"""sanskruti_updates

Revision ID: b1332fb8dec5
Revises: 943dee823e07
Create Date: 2026-07-20 11:21:03.417862
"""
from alembic import op
import sqlalchemy as sa
import app.database.types


revision = 'b1332fb8dec5'
down_revision = '943dee823e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_ledger',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_id', app.database.types.GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payment_mode', sa.String(length=20), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory_units', sa.Column('plc_charges', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('inventory_units', sa.Column('plot_facing', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('budget', sa.String(length=64), nullable=True))
    op.add_column('leads', sa.Column('preferred_plot_size', sa.String(length=64), nullable=True))
    op.add_column('leads', sa.Column('preferred_plot_type', sa.String(length=32), nullable=True))
    op.add_column('leads', sa.Column('preferred_location', sa.String(length=128), nullable=True))
    op.add_column('leads', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'remarks')
    op.drop_column('leads', 'preferred_location')
    op.drop_column('leads', 'preferred_plot_type')
    op.drop_column('leads', 'preferred_plot_size')
    op.drop_column('leads', 'budget')
    op.drop_column('inventory_units', 'plot_facing')
    op.drop_column('inventory_units', 'plc_charges')
    op.drop_table('expense_ledger')
    # ### end Alembic commands ###
